services:
  nats:
    container_name: nats
    image: nats:latest
    restart: always
    command: -c /nats/config.conf  --js --sd /data
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    volumes:
      - data:/data
      - ./config.conf:/nats/config.conf

volumes:
  data:
