services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    restart: always
    ulimits:
      memlock: -1
    environment:
      CLICKHOUSE_USER: dev
      CLICKHOUSE_PASSWORD: dev
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - data:/var/lib/clickhouse
      - logs:/var/log/clickhouse-server

volumes:
  data:
  logs:
