services:
  edgedb:
    container_name: edgedb
    image: edgedb/edgedb:latest
    restart: always
    environment:
      EDGEDB_SERVER_PASSWORD: dev
      EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
    ports:
      - 5656:5656
    volumes:
      - data:/var/lib/edgedb/data

volumes:
  data:
