services:
  kvrocks:
    image: apache/kvrocks:latest
    restart: always
    environment:
      KVROCKS_ADMIN_SECRET: dev
    ports:
      - 6666:6666
    volumes:
      - data:/var/lib/kvrocks

volumes:
  data:
