services:
  yugabytedb:
    image: yugabytedb/yugabyte:latest
    container_name: yugabytedb
    restart: always
    environment:
      YSQL_USER: dev
      YSQL_PASSWORD: dev
      YCQL_USER: dev
      YCQL_PASSWORD: dev
    command: >
      bin/yugabyted start
      --base_dir=/home/yugabyte/yb_data
      --background=false
    ports:
      - 7000:7000
      - 9000:9000
      - 15433:15433
      - 5433:5433
      - 9042:9042
    volumes:
      - data:/home/yugabyte/yb_data

volumes:
  data:
