services:
  pocketbase:
    container_name: pocketbase
    image: ghcr.io/muchobien/pocketbase:latest
    restart: always
    environment:
      ENCRYPTION: example #optional
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    ports:
      - 8090:8090
    volumes:
      - data:/pb_data
      - data:/pb_public #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
