services:
  ydb:
    container_name: ydb
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    platform: linux/amd64
    restart: always
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_USE_IN_MEMORY_PDISKS: false
    hostname: localhost
    ports:
      - 2135:2135
      - 2136:2136
      - 8765:8765
    volumes:
      - data:/ydb_certs
      - data:/ydb_data

volumes:
  data:
